# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre Completo')),
                ('razon_social', models.CharField(max_length=255, verbose_name='Raz\xf3n Social')),
                ('identificacion', models.CharField(choices=[('1', 'CEDULA'), ('2', 'RUC')], max_length=1, verbose_name='Tipo de Identificacion')),
                ('cedula', models.CharField(max_length=20, verbose_name='Cedula')),
                ('genero', models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMENINO')], max_length=1, verbose_name='Genero')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo')),
                ('telefono', models.PositiveIntegerField(max_length=15, verbose_name='Telefono')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Provedores',
            },
        ),
    ]
