# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0002_auto_20170724_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(max_length=10, verbose_name='Telefono'),
        ),
    ]
