# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0003_auto_20170724_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='archivado',
            field=models.BooleanField(default=False, verbose_name='Archivado?'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='deshabilitado',
            field=models.BooleanField(default=False, verbose_name='Deshabilitado?'),
        ),
    ]
