# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 07:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0004_auto_20170726_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='deshabilitado',
        ),
    ]
